<?php

namespace PLL\CoreBundle\Repository;

/**
 * BuildRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BuildRepository extends \Doctrine\ORM\EntityRepository
{
	public function getBuildsWithPreferences($guild_id) 
	{
		$query = $this
			->createQueryBuilder("b")
			->where("b.guild = ?1")
			->leftJoin("b.preferences", "p")
			->addSelect("p")
			->setParameter(1, $guild_id)
		;

		return $query
			->getQuery()
			->getResult()
		;
	}
}
