<?php

namespace PLL\CoreBundle\Repository;

/**
 * BuildRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BuildRepository extends \Doctrine\ORM\EntityRepository
{
}
