<?php

namespace PLL\CoreBundle\Repository;

/**
 * CompositionGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompositionGroupRepository extends \Doctrine\ORM\EntityRepository
{
}
