<?php

namespace PLL\CoreBundle\Repository;

/**
 * CompositionBuildRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompositionBuildRepository extends \Doctrine\ORM\EntityRepository
{
}
