<?php

namespace PLL\CoreBundle\Repository;

/**
 * CompositionGroupBuildRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompositionGroupBuildRepository extends \Doctrine\ORM\EntityRepository
{
}
