pll_core_welcome:
    path:     /
    defaults:
    defaults: { _controller: PLLCoreBundle:Default:welcome, _locale: en }

pll_core_landing:
    path:     /{_locale}/
    defaults: { _controller: PLLCoreBundle:Default:landing, _locale: en }
    requirements:
        _locale: en|fr

pll_core_home:
    path:     /{_locale}/home
    defaults: { _controller: PLLCoreBundle:Guild:home, _locale: en }
    requirements:
        _locale: en|fr

pll_core_delete_apikey:
    path:     /{_locale}/home/delete-apikey
    defaults: { _controller: PLLCoreBundle:Guild:delete, _locale: en }
    requirements:
        _locale: en|fr

pll_core_team_home:
    path:     /{_locale}/team
    defaults: { _controller: PLLCoreBundle:Team:team, _locale: en }
    requirements:
        _locale: en|fr

pll_core_events:
    path:     /{_locale}/events
    defaults: { _controller: PLLCoreBundle:Event:events, _locale: en }
    requirements:
        _locale: en|fr

pll_core_events_new:
    path:     /{_locale}/events/new
    defaults: { _controller: PLLCoreBundle:Event:newevent, _locale: en }
    requirements:
        _locale: en|fr

pll_core_events_edit:
    path:     /{_locale}/events/edit/{id}
    defaults: { _controller: PLLCoreBundle:Event:editevent, _locale: en }
    requirements:
        _locale: en|fr
        id: \d+

pll_core_events_delete:
    path:     /{_locale}/events/delete/{id}
    defaults: { _controller: PLLCoreBundle:Event:deleteevent, _locale: en }
    requirements:
        _locale: en|fr
        id: \d+

pll_core_players:
    path:     /{_locale}/players
    defaults: { _controller: PLLCoreBundle:Player:players, _locale: en }
    requirements:
        _locale: en|fr

pll_core_players_new:
    path:     /{_locale}/players/new
    defaults: { _controller: PLLCoreBundle:Player:newplayer, _locale: en }
    requirements:
        _locale: en|fr

pll_core_players_edit:
    path:     /{_locale}/players/edit/{id}
    defaults: { _controller: PLLCoreBundle:Player:editplayer, _locale: en }
    requirements:
        _locale: en|fr
        id: \d+

pll_core_players_delete:
    path:     /{_locale}/players/delete/{id}
    defaults: { _controller: PLLCoreBundle:Player:deleteplayer, _locale: en }
    requirements:
        _locale: en|fr
        id: \d+

pll_core_compositions:
    path:     /{_locale}/compositions
    defaults: { _controller: PLLCoreBundle:Composition:compositions, _locale: en }
    requirements:
        _locale: en|fr

pll_core_compositions_new:
    path:     /{_locale}/compositions/new
    defaults: { _controller: PLLCoreBundle:Composition:newcomposition, _locale: en }
    requirements:
        _locale: en|fr

pll_core_compositions_edit:
    path:     /{_locale}/compositions/edit/{id}
    defaults: { _controller: PLLCoreBundle:Composition:editcomposition, _locale: en }
    requirements:
        _locale: en|fr
        id: \d+

pll_core_compositions_delete:
    path:     /{_locale}/compositions/delete/{id}
    defaults: { _controller: PLLCoreBundle:Composition:deletecomposition, _locale: en }
    requirements:
        _locale: en|fr
        id: \d+

pll_core_builds:
    path:     /{_locale}/builds
    defaults: { _controller: PLLCoreBundle:Build:build, _locale: en }
    requirements:
        _locale: en|fr

pll_core_builds_new:
    path:     /{_locale}/builds/new
    defaults: { _controller: PLLCoreBundle:Build:newbuild, _locale: en }
    requirements:
        _locale: en|fr

pll_core_builds_add_default:
    path:     /{_locale}/builds/add-default
    defaults: { _controller: PLLCoreBundle:Build:adddefault, _locale: en }
    requirements:
        _locale: en|fr

pll_core_builds_edit:
    path:     /{_locale}/builds/edit/{id}
    defaults: { _controller: PLLCoreBundle:Build:editbuild, _locale: en }
    requirements:
        _locale: en|fr
        id: \d+

pll_core_builds_delete:
    path:     /{_locale}/builds/delete/{id}
    defaults: { _controller: PLLCoreBundle:Build:deletebuild, _locale: en }
    requirements:
        _locale: en|fr
        id: \d+