pll_core_landing:
    path:     /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: pll_core_home
        permanent: true

pll_core_home:
    path:     /{_locale}/
    defaults: { _controller: PLLCoreBundle:Default:home, _locale: en }
    requirements:
        _locale: fr|en

pll_core_admin_home:
    path:     /admin
    defaults: { _controller: PLLCoreBundle:Admin:home }