pll_core_welcome:
    path:     /
    defaults:
    defaults: { _controller: PLLCoreBundle:Default:welcome, _locale: en }

pll_core_landing:
    path:     /{_locale}/
    defaults: { _controller: PLLCoreBundle:Default:landing, _locale: en }
    requirements:
        _locale: fr|en

pll_core_home:
    path:     /{_locale}/home
    defaults: { _controller: PLLCoreBundle:Guild:home, _locale: en }
    requirements:
        _locale: fr|en

pll_core_admin_home:
    path:     /admin
    defaults: { _controller: PLLCoreBundle:Admin:home }