services:
    pll_core.buildfactory:
        class: PLL\CoreBundle\Factory\BuildFactory
    pll_core.defaultbuilds:
        class: PLL\CoreBundle\Service\DefaultBuilds
        arguments:
          - "@pll_core.buildfactory"
    pll_core.team.validator:
        class: PLL\CoreBundle\Team\Validator\TeamValidator
    pll_core.team.builder:
        class: PLL\CoreBundle\Team\Builder\TeamBuilder
    pll_core.analytics.composition:
        class: PLL\CoreBundle\Analytics\CompositionAnalytics
    pll_core.analytics.player:
        class: PLL\CoreBundle\Analytics\PlayerAnalytics