services:
    pll_core.buildfactory:
        class: PLL\CoreBundle\Factory\BuildFactory
    pll_core.defaultbuilds:
        class: PLL\CoreBundle\Service\DefaultBuilds
        arguments:
          - "@pll_core.buildfactory"
    pll_core.team.validator:
        class: PLL\CoreBundle\Team\Validator\TeamValidator